import type { Peptideo, Objetivo } from "@/types";

export const OM: Record<string, string> = {
  gordura: "Perda de gordura",
  massa: "Ganho de massa",
  recuperacao: "Recuperação",
  sono: "Sono",
  pele: "Saúde da pele",
  longevidade: "Longevidade",
  cognitivo: "Cognitivo",
  hormonal: "Hormonal",
};

export const DM: Record<string, string> = {
  "4sem": "4 semanas",
  "8sem": "8 semanas",
  "12sem": "12 semanas",
  continuo: "Contínuo",
};

export const SM: Record<string, string> = {
  "4sem": "4sem",
  "8sem": "8sem",
  "12sem": "12sem",
  continuo: "∞",
};

export const NM: Record<string, string> = {
  iniciante: "Iniciante",
  intermediario: "Intermediário",
  avancado: "Avançado",
};

export const EM: Record<string, string> = {
  sedentario: "Sedentário",
  moderado: "Ativo moderado",
  ativo: "Ativo",
  atleta: "Atleta",
};

export const PEPTIDES: Record<Objetivo, Peptideo[]> = {
  gordura: [
    {
      e: "🔥",
      n: "AOD-9604",
      m: "Fragmento do GH (176–191) — lipólise seletiva sem efeitos anabólicos",
      why: "Você quer perder gordura: o AOD-9604 age diretamente no tecido adiposo sem interferir no seu eixo hormonal.",
      base: 4,
      unit: "mcg/kg",
      doseStr: (p) => `${Math.round(p * 4)}mcg`,
      freq: "1x ao dia",
      timing: "Manhã, em jejum completo",
      route: "SC — abdômen ou coxa",
      cycle: "8–12 semanas",
      rest: "4 sem de pausa",
      how: "Reconstituir com 1–2ml de água bacteriostática. Jejum obrigatório antes e por 30min após.",
      ck: true,
    },
    {
      e: "⚖️",
      n: "Tirzepatide",
      m: "Agonista duplo GIP/GLP-1 — controle de apetite e metabolismo",
      why: "Para perda de gordura mais agressiva: age no cérebro reduzindo fome e no pâncreas melhorando sensibilidade à insulina.",
      base: null,
      unit: "mg fixo",
      doseStr: () => "2.5–15mg",
      freq: "1x por semana",
      timing: "Qualquer dia da semana, mesmo horário",
      route: "SC — abdômen, coxa ou braço",
      cycle: "12–24 semanas",
      rest: "Avaliação médica",
      how: "Iniciar com 2.5mg/sem. Aumentar 2.5mg a cada 4 semanas conforme tolerância.",
      ck: true,
    },
    {
      e: "💧",
      n: "Ipamorelin",
      m: "Secretagogo do GH — melhora composição corporal e metabolismo",
      why: "Combinado com AOD para otimizar composição: o Ipamorelin eleva GH, que melhora a proporção músculo/gordura.",
      base: 2.5,
      unit: "mcg/kg",
      doseStr: (p) => `${Math.round(p * 2.5)}mcg`,
      freq: "3x por semana",
      timing: "Noite, antes de dormir",
      route: "SC — abdômen",
      cycle: "8–12 semanas",
      rest: "4 sem",
      how: "Combinar com CJC-1295 para efeito sinérgico. Sempre em jejum antes da aplicação.",
      ck: false,
    },
  ],
  massa: [
    {
      e: "💪",
      n: "Ipamorelin",
      m: "Secretagogo do GH — estímulo anabólico limpo e consistente",
      why: "Para ganho de massa: o Ipamorelin eleva o GH de forma pulsátil, estimulando síntese proteica e recuperação muscular.",
      base: 2.5,
      unit: "mcg/kg",
      doseStr: (p) => `${Math.round(p * 2.5)}mcg`,
      freq: "5x por semana",
      timing: "Ao acordar e antes de dormir",
      route: "SC — abdômen ou coxa",
      cycle: "12 semanas",
      rest: "4 sem",
      how: "3 aplicações diárias nos dias de treino. Sempre em jejum.",
      ck: true,
    },
    {
      e: "🌿",
      n: "CJC-1295 (sem DAC)",
      m: "Amplificador de GHRH — sinérgico com Ipamorelin para pico de GH",
      why: "CJC amplifica o sinal do GHRH — combinado com Ipamorelin cria um pico de GH muito maior do que cada um separado.",
      base: 1.5,
      unit: "mcg/kg",
      doseStr: (p) => `${Math.round(p * 1.5)}mcg`,
      freq: "5x por semana",
      timing: "Combinado com Ipamorelin, mesmos horários",
      route: "SC — abdômen",
      cycle: "12 semanas",
      rest: "4 sem",
      how: "Sempre em combinação com Ipamorelin. Evitar alimentos 1h antes/após.",
      ck: false,
    },
    {
      e: "🔄",
      n: "BPC-157",
      m: "Peptídeo citoprotetor — recuperação muscular acelerada e suporte tendinoso",
      why: "Treino intenso gera microlesões — o BPC-157 acelera o reparo de tecidos e reduz dor pós-treino.",
      base: 3.5,
      unit: "mcg/kg",
      doseStr: (p) => `${Math.round(p * 3.5)}mcg`,
      freq: "5x por semana",
      timing: "Pode ser tomado com ou sem jejum",
      route: "SC perto do músculo alvo (ou oral)",
      cycle: "4–6 semanas",
      rest: "2 sem",
      how: "Para uso oral: dissolver em água. Para SC: aplicar próximo à área trabalhada.",
      ck: false,
    },
  ],
  recuperacao: [
    {
      e: "🔄",
      n: "BPC-157",
      m: "Regeneração sistêmica de tecidos moles, articulações e tendões",
      why: "Para recuperação: o BPC-157 age em múltiplos tecidos simultaneamente — músculos, tendões, ligamentos e mucosa intestinal.",
      base: 3.5,
      unit: "mcg/kg",
      doseStr: (p) => `${Math.round(p * 3.5)}mcg`,
      freq: "5x por semana",
      timing: "Com ou sem jejum, 2x ao dia nos dias de uso",
      route: "SC próximo à área lesionada",
      cycle: "4–8 semanas",
      rest: "2–4 sem",
      how: "Aplicar o mais próximo possível da região lesionada. Via oral funciona para intestino/estômago.",
      ck: true,
    },
    {
      e: "🩺",
      n: "TB-500",
      m: "Fator de crescimento tecidual — reparo de lesões crônicas e agudas",
      why: "TB-500 age em lesões que resistem ao tratamento convencional — migração celular e formação de novos vasos.",
      base: null,
      unit: "mg fixo",
      doseStr: () => "2mg",
      freq: "2x por semana (indução), 1x/sem (manutenção)",
      timing: "Qualquer horário, com ou sem jejum",
      route: "SC ou IM",
      cycle: "4 sem de indução + 8 sem manutenção",
      rest: "4 sem",
      how: "Semanas 1–4: 2mg 2x/semana. Semanas 5+: 2mg 1x/semana.",
      ck: false,
    },
  ],
  sono: [
    {
      e: "🌙",
      n: "DSIP",
      m: "Modula ciclos de sono NREM, reduz cortisol noturno",
      why: "Para melhorar o sono: o DSIP regula as fases mais profundas do sono, onde ocorre a maior recuperação hormonal.",
      base: 2,
      unit: "mcg/kg",
      doseStr: (p) => `${Math.round(p * 2)}mcg`,
      freq: "4x por semana",
      timing: "30 min antes de dormir",
      route: "SC — abdômen",
      cycle: "4–6 semanas",
      rest: "2–4 sem",
      how: "Não usar todas as noites para não dessensibilizar. Ciclar: 4 noites sim, 3 noites não.",
      ck: true,
    },
    {
      e: "🌟",
      n: "Epithalon",
      m: "Regulação do telômero e melhora do ritmo circadiano",
      why: "Epithalon regula o gene da melatonina e o ritmo circadiano — sono mais profundo e restaurador ao longo do tempo.",
      base: null,
      unit: "mg fixo",
      doseStr: () => "10mg total",
      freq: "1x ao dia (5 dias consecutivos)",
      timing: "Qualquer horário",
      route: "SC ou IV",
      cycle: "Curso de 5 dias, 2x ao ano",
      rest: "6 meses entre cursos",
      how: "Protocolo semestral. Dose de 2mg/dia por 5 dias = 10mg total.",
      ck: false,
    },
  ],
  pele: [
    {
      e: "✨",
      n: "GHK-Cu",
      m: "Estimula síntese de colágeno, elastina e ativa células-tronco dérmicas",
      why: "Para saúde da pele: o GHK-Cu é o peptídeo mais estudado para regeneração cutânea — ativa mais de 4.000 genes de reparo celular.",
      base: 1,
      unit: "mg/dia",
      doseStr: () => "1–2mg",
      freq: "3–5x por semana",
      timing: "Qualquer horário",
      route: "SC — rosto/pescoço ou tópico (solução 0.1–0.5%)",
      cycle: "8–12 semanas",
      rest: "4 sem",
      how: "Via SC: 1mg 3x/semana. Via tópica: aplicar solução 0.1–0.5% 2x ao dia, após limpeza.",
      ck: true,
    },
    {
      e: "🩹",
      n: "BPC-157",
      m: "Cicatrização acelerada, redução de inflamação cutânea",
      why: "O BPC-157 tem ação anti-inflamatória direta na pele — excelente para cicatrizes, rosácea e dermatites.",
      base: 3,
      unit: "mcg/kg",
      doseStr: (p) => `${Math.round(p * 3)}mcg`,
      freq: "3x por semana",
      timing: "Tópico ou SC próximo à área",
      route: "SC próximo ao local ou tópico",
      cycle: "4–6 semanas",
      rest: "2 sem",
      how: "Para pele: pode ser usada solução tópica ou aplicação SC peri-lesional.",
      ck: false,
    },
    {
      e: "🌸",
      n: "KPV",
      m: "Tripeptídeo anti-inflamatório — controle de pele inflamatória e intestinal",
      why: "Se você tem acne, rosácea ou pele sensível, o KPV reduz a inflamação local sem efeitos sistêmicos.",
      base: null,
      unit: "mg fixo",
      doseStr: () => "0.5–2mg",
      freq: "1–2x ao dia",
      timing: "Manhã e noite",
      route: "Tópico ou oral",
      cycle: "8–12 semanas",
      rest: "4 sem",
      how: "Via tópica: solução 0.1–0.5% na área afetada.",
      ck: false,
    },
  ],
  longevidade: [
    {
      e: "🌟",
      n: "Epithalon",
      m: "Regula telômeros, estimula telomerase — principal peptídeo antienvelhecimento",
      why: "Para longevidade: Epithalon é o único composto capaz de reativar a telomerase — a enzima que protege o comprimento dos telômeros.",
      base: null,
      unit: "mg fixo",
      doseStr: () => "10mg total",
      freq: "Curso de 5 dias, 2x ao ano",
      timing: "Qualquer horário",
      route: "SC (2mg/dia) ou IV (10mg dose única)",
      cycle: "5 dias",
      rest: "6 meses",
      how: "Protocolo mais eficaz: 2mg SC por 5 dias consecutivos. Repetir a cada 6 meses.",
      ck: true,
    },
    {
      e: "🛡️",
      n: "Thymosin Alpha-1",
      m: "Imunomodulador — maturação de células T, imunidade adaptativa",
      why: "Para longevidade, a imunidade é fundamental. O Tα1 treina o sistema imune a responder melhor e com menos inflamação crônica.",
      base: null,
      unit: "mg fixo",
      doseStr: () => "1.6mg",
      freq: "2x por semana",
      timing: "Qualquer horário, com ou sem jejum",
      route: "SC — abdômen",
      cycle: "4–6 semanas",
      rest: "4–8 sem",
      how: "1.6mg SC 2x/semana.",
      ck: false,
    },
    {
      e: "⚡",
      n: "NAD+",
      m: "Cofator essencial — reparo de DNA, produção energética mitocondrial",
      why: "NAD+ declina com a idade — suplementar é uma das estratégias mais estudadas para reverter marcadores de envelhecimento celular.",
      base: null,
      unit: "mg fixo",
      doseStr: () => "250–500mg",
      freq: "1x ao dia",
      timing: "Manhã, com ou sem jejum",
      route: "Oral, sublingual ou IV",
      cycle: "Uso contínuo ou ciclos de 12 semanas",
      rest: "4 sem (se ciclar)",
      how: "Via oral: 250–500mg pela manhã. Via IV: 250mg em infusão lenta (2–4h).",
      ck: false,
    },
  ],
  cognitivo: [
    {
      e: "🧠",
      n: "Selank",
      m: "Análogo da tuftosina — modulação da ansiedade, clareza mental, neuroproteção",
      why: "Para performance cognitiva: o Selank modula o GABA e reduz o ruído mental, melhorando foco sem efeito estimulante clássico.",
      base: 3,
      unit: "mcg/kg",
      doseStr: (p) => `${Math.round(p * 3)}mcg`,
      freq: "5x por semana",
      timing: "Manhã e início da tarde",
      route: "SC ou intranasal (0.15% = 250mcg/spray)",
      cycle: "4–6 semanas",
      rest: "2–3 sem",
      how: "Via intranasal: 2–3 sprays por narina, 2x ao dia. Via SC: dose calculada por peso.",
      ck: true,
    },
    {
      e: "⚡",
      n: "Semax",
      m: "Análogo do ACTH — neurotropismo, foco, memória, neuroproteção pós-lesão",
      why: "Para memória e foco: o Semax aumenta o BDNF — fator de crescimento neural que melhora plasticidade e recuperação cognitiva.",
      base: null,
      unit: "mcg fixo",
      doseStr: () => "300–600mcg",
      freq: "5x por semana",
      timing: "Manhã, em jejum",
      route: "Intranasal (solução 0.1%)",
      cycle: "4 semanas",
      rest: "2 sem",
      how: "Solução intranasal 0.1%: 3–6 sprays por narina de manhã. Não usar à noite.",
      ck: false,
    },
  ],
  hormonal: [
    {
      e: "⚗️",
      n: "Ipamorelin",
      m: "Secretagogo do GH — otimização do eixo GH/IGF-1",
      why: "Para equilíbrio hormonal: o Ipamorelin restaura a pulsatilidade do GH, que declina com a idade e afeta energia, libido e composição.",
      base: 2.5,
      unit: "mcg/kg",
      doseStr: (p) => `${Math.round(p * 2.5)}mcg`,
      freq: "3x por semana",
      timing: "Antes de dormir",
      route: "SC",
      cycle: "8–12 semanas",
      rest: "4 sem",
      how: "Para otimização hormonal: uso noturno alinhado com o pico fisiológico de GH durante o sono.",
      ck: true,
    },
    {
      e: "💜",
      n: "PT-141 (Bremelanotide)",
      m: "Agonista do receptor de melanocortina — libido e função sexual",
      why: "Para equilíbrio hormonal completo: o PT-141 age diretamente no cérebro melhorando libido sem impactar pressão arterial.",
      base: null,
      unit: "mg fixo",
      doseStr: () => "1–2mg",
      freq: "Conforme necessidade (máx 3x/sem)",
      timing: "1–2h antes da atividade sexual",
      route: "SC — abdômen ou intranasal",
      cycle: "Uso pontual ou ciclos curtos",
      rest: "Sem uso diário",
      how: "SC: 1mg até 2h antes. Intranasal: 1 spray. Iniciar com 0.5mg.",
      ck: false,
    },
    {
      e: "🔬",
      n: "Tesamorelin",
      m: "Análogo do GHRH — aprovado FDA para redistribuição de gordura visceral",
      why: "Para hormonal e gordura visceral: Tesamorelin é o único peptídeo aprovado pela FDA especificamente para redução de gordura abdominal.",
      base: null,
      unit: "mg fixo",
      doseStr: () => "1–2mg",
      freq: "1x ao dia",
      timing: "Antes de dormir",
      route: "SC — abdômen",
      cycle: "26 semanas",
      rest: "Avaliação médica",
      how: "1–2mg SC antes de dormir. Monitorar IGF-1 a cada 8 semanas.",
      ck: false,
    },
  ],
};

export function buildProtocol(objetivos: Objetivo[], peso: number): Peptideo[] {
  const all: Peptideo[] = [];
  const seen = new Set<string>();
  objetivos.forEach((obj) => {
    (PEPTIDES[obj] || []).forEach((p) => {
      if (!seen.has(p.n)) {
        seen.add(p.n);
        all.push(p);
      }
    });
  });
  return all;
}
