
-- ═══════════════════════════════════════════════════════
-- TABELA PEPTIDEOS — Base educativa completa da Nuvita
-- ═══════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.peptideos (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  slug text UNIQUE NOT NULL,
  nome text NOT NULL,
  emoji text DEFAULT '💊',
  categoria text NOT NULL,
  subcategoria text,
  nivel text DEFAULT 'iniciante', -- iniciante, intermediario, avancado
  resumo text,
  mecanismo text,
  indicacoes text[],
  contraindicacoes text[],
  dose_min numeric DEFAULT 0,
  dose_max numeric DEFAULT 0,
  unidade text DEFAULT 'mcg',
  frequencia text,
  via text DEFAULT 'SC',
  ciclo text,
  meia_vida text,
  armazenamento text,
  sinergias text[],
  antagonismos text[],
  estudos text[],
  tags text[],
  destaque boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.peptideos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "peptideos_publicos" ON public.peptideos FOR SELECT TO anon, authenticated USING (true);

-- ═══════════════════════════════════════════════════════
-- DADOS — 30 peptídeos com fichas completas
-- ═══════════════════════════════════════════════════════

INSERT INTO public.peptideos (slug, nome, emoji, categoria, subcategoria, nivel, resumo, mecanismo, indicacoes, contraindicacoes, dose_min, dose_max, unidade, frequencia, via, ciclo, meia_vida, armazenamento, sinergias, antagonismos, estudos, tags, destaque) VALUES

('bpc-157', 'BPC-157', '🔵', 'Recuperação', 'Regeneração tecidual', 'iniciante',
'Pentadecapeptídeo de proteção corporal derivado do suco gástrico humano. Um dos peptídeos com maior espectro de ação terapêutica.',
'Ativa receptores de fatores de crescimento (VEGF, EGF), estimula angiogênese, modula óxido nítrico e protege mucosa gástrica. Age sistemicamente mesmo por vias oral e subcutânea.',
ARRAY['Recuperação de lesões musculares e tendíneas','Proteção e reparo gástrico','Anti-inflamatório sistêmico','Saúde articular','Recuperação pós-cirúrgica'],
ARRAY['Histórico de câncer (estímulo angiogênico)','Gravidez e lactação'],
250, 500, 'mcg', '1-2x ao dia', 'SC ou oral', '4-12 semanas',
'~4 horas (SC)', 'Refrigerado, protegido da luz',
ARRAY['TB-500','GHK-Cu','Semaglutida (proteção gástrica)'],
ARRAY['NSAIDs em altas doses (pode antagonizar proteção gástrica)'],
ARRAY['Sikiric P. et al. (2018) - Stable gastric pentadecapeptide BPC 157 in clinical trials','Gwyer D. et al. (2019) - Gastric pentadecapeptide body protection compound BPC 157'],
ARRAY['regeneração','tendão','músculo','gástrico','anti-inflamatório'], true),

('tb-500', 'TB-500', '🟣', 'Recuperação', 'Reparo celular', 'intermediario',
'Fração sintética da Timosina Beta-4, proteína naturalmente presente em todas as células do corpo humano. Especializada em reparo de tecidos.',
'Regula a actina celular, promovendo migração e diferenciação de células progenitoras para locais de lesão. Estimula angiogênese e reduz fibrose. Age via upregulation do gene PINCH.',
ARRAY['Lesões musculares agudas e crônicas','Tendinites e fascites','Recuperação pós-cirúrgica','Doenças cardíacas (pesquisa)','Reparo neural'],
ARRAY['Histórico de câncer','Gravidez'],
2000, 2500, 'mcg', '2x por semana (fase de carga)', 'SC', '4-6 semanas carga, manutenção variável',
'~24 horas', 'Refrigerado após reconstituição',
ARRAY['BPC-157','GHK-Cu'],
ARRAY[],
ARRAY['Goldstein AL. et al. (2005) - Thymosin beta4: a multifunctional regenerative peptide','Bock-Marquette I. et al. (2004) - Thymosin beta4 activates integrin-linked kinase'],
ARRAY['recuperação','lesão','tendão','fibrose','angiogênese'], true),

('ghk-cu', 'GHK-Cu', '🟤', 'Anti-aging', 'Reparo dérmico', 'iniciante',
'Tripeptídeo de cobre (glicil-L-histidil-L-lisina) que declina com a idade e é responsável por múltiplos processos de reparo e rejuvenescimento.',
'Liga-se ao cobre plasmático e o transporta para células que necessitam. Ativa mais de 4.000 genes, incluindo síntese de colágeno, elastina, proteoglicanos e genes de reparo do DNA. Suprime genes inflamatórios e oncogenes.',
ARRAY['Antienvelhecimento cutâneo','Estímulo de síntese de colágeno','Queda capilar (alopecia androgenética)','Cicatrização de feridas','Regeneração neural'],
ARRAY['Hipersensibilidade ao cobre'],
1000, 2000, 'mcg', '1x ao dia', 'SC ou tópico', '8-12 semanas',
'~30 minutos (plasmática)', 'Temperatura ambiente (forma seca), refrigerado após reconstituição',
ARRAY['BPC-157','TB-500'],
ARRAY[],
ARRAY['Pickart L. et al. (2015) - GHK-Cu Peptide: a human skin remodeling signal','Pickart L. et al. (2012) - The human tri-peptide GHK and tissue remodeling'],
ARRAY['colágeno','pele','cabelo','antienvelhecimento','cobre'], false),

('semaglutida', 'Semaglutida', '🔴', 'Emagrecimento', 'Análogo GLP-1', 'iniciante',
'Análogo sintético do GLP-1 (glucagon-like peptide-1) com modificação estrutural que aumenta a meia-vida de minutos para dias. O mais eficaz peptídeo para perda de peso aprovado clinicamente.',
'Ativa receptores GLP-1 no hipotálamo reduzindo apetite, no pâncreas estimulando insulina glicose-dependente, e no estômago retardando esvaziamento gástrico. Reduz inflamação sistêmica e tem efeitos cardiovasculares protetores.',
ARRAY['Perda de gordura corporal','Diabetes tipo 2','Síndrome metabólica','Proteção cardiovascular','Esteatose hepática (NASH)'],
ARRAY['Histórico de carcinoma medular de tireoide','NEM tipo 2','Pancreatite aguda','Gravidez'],
250, 2400, 'mcg', '1x por semana', 'SC', 'Contínuo (uso clínico)',
'~7 dias', 'Refrigerado, não congelar',
ARRAY['Tirzepatida (não combinar - mesmo mecanismo)'],
ARRAY['Insulina (ajuste de dose necessário)','Medicamentos com esvaziamento gástrico acelerado'],
ARRAY['Wilding JPH et al. (2021) - Once-Weekly Semaglutide in Adults with Overweight or Obesity (STEP 1)','Marso SP et al. (2016) - Semaglutide and Cardiovascular Outcomes in Patients with Type 2 Diabetes (SUSTAIN-6)'],
ARRAY['GLP-1','emagrecimento','diabetes','metabolismo','saciedade'], true),

('tirzepatida', 'Tirzepatida', '🎯', 'Emagrecimento', 'Agonista duplo GLP-1/GIP', 'intermediario',
'Primeiro agonista duplo GLP-1/GIP da história. Age em dois receptores simultaneamente, produzindo perda de peso superior a qualquer monoterapia existente.',
'Ativa receptores GLP-1 (redução de apetite, insulinotrópico) e GIP (melhora sensibilidade insulínica, redução de gordura visceral, efeito neurológico direto no apetite). A combinação produz efeitos sinérgicos não observados com agonistas isolados.',
ARRAY['Perda de gordura avançada','Diabetes tipo 2 (aprovado FDA)','Obesidade grave','Síndrome metabólica'],
ARRAY['Histórico de carcinoma medular de tireoide','NEM tipo 2','Pancreatite','Gravidez'],
2500, 15000, 'mcg', '1x por semana', 'SC', 'Contínuo',
'~5 dias', 'Refrigerado',
ARRAY[],
ARRAY['Semaglutida (não combinar)','Outros agonistas GLP-1'],
ARRAY['Jastreboff AM et al. (2022) - Tirzepatide Once Weekly for the Treatment of Obesity (SURMOUNT-1)','Frías JP et al. (2021) - Tirzepatide versus Semaglutide Once Weekly in Patients with Type 2 Diabetes (SURPASS-2)'],
ARRAY['GLP-1','GIP','emagrecimento','duplo agonista','diabetes'], true),

('cjc-1295', 'CJC-1295', '🟡', 'GH/Composição', 'Análogo GHRH', 'intermediario',
'Análogo sintético do GHRH (hormônio liberador de GH) com conjugação DAC que aumenta drasticamente sua meia-vida. Estimula liberação pulsátil de GH.',
'Liga-se a albumina plasmática via DAC (Drug Affinity Complex), aumentando meia-vida de minutos (GHRH natural) para 8 dias. Estimula receptores GHRH na hipófise anterior, aumentando amplitude dos pulsos de GH sem alterar frequência.',
ARRAY['Aumento de massa magra','Redução de gordura corporal','Melhora de recuperação','Anti-aging','Melhora da densidade óssea'],
ARRAY['Acromegalia','Câncer ativo','Diabetes não controlada','Hipotiroidismo não tratado'],
1000, 2000, 'mcg', '1-2x por semana (versão DAC)', 'SC', '8-16 semanas',
'~8 dias (versão DAC)', 'Refrigerado após reconstituição',
ARRAY['Ipamorelin','GHRP-6','GHRP-2'],
ARRAY['Somatostatina (antagonismo fisiológico)','Insulina elevada'],
ARRAY['Teichman SL et al. (2006) - Prolonged stimulation of growth hormone (GH) and insulin-like growth factor I secretion by CJC-1295'],
ARRAY['GH','GHRH','composição corporal','massa muscular','anti-aging'], true),

('ipamorelin', 'Ipamorelin', '🟢', 'GH/Composição', 'Secretagogo seletivo', 'iniciante',
'Secretagogo de GH mais seletivo disponível. Imita grelina mas sem os efeitos colaterais indesejados como aumento de cortisol, prolactina ou ACTH.',
'Agonista seletivo do receptor de grelina (GHS-R1a) que estimula a liberação pulsátil de GH pela hipófise anterior. Não afeta cortisol, prolactina, ACTH ou hormônios tireoidianos — perfil de segurança superior a outros secretagogos.',
ARRAY['Estímulo de GH pulsátil fisiológico','Composição corporal','Melhora do sono','Recuperação','Bem-estar geral'],
ARRAY['Câncer ativo','Gravidez','Acromegalia'],
200, 300, 'mcg', '2-3x ao dia (jejum ou antes de dormir)', 'SC', '8-16 semanas',
'~2 horas', 'Refrigerado após reconstituição',
ARRAY['CJC-1295','GHRP-2','MOD-GRF(1-29)'],
ARRAY[],
ARRAY['Raun K et al. (1998) - Ipamorelin, the first selective growth hormone secretagogue','Bowers CY et al. - GH-releasing peptides and GH secretagogues'],
ARRAY['GH','secretagogo','sono','recuperação','composição corporal'], true),

('aod-9604', 'AOD-9604', '🔥', 'Emagrecimento', 'Fragmento HGH', 'iniciante',
'Fragmento C-terminal do hormônio do crescimento humano (HGH) que retém apenas as propriedades lipolíticas, sem os efeitos proliferativos do GH completo.',
'Liga-se a receptores específicos no tecido adiposo, ativando lipólise (quebra de gordura) e inibindo lipogênese (formação de gordura). Não afeta IGF-1, glicemia nem receptores de insulina — segurança superior ao HGH para fins de emagrecimento.',
ARRAY['Redução de gordura localizada','Aumento de metabolismo basal','Preservação de massa magra durante cutting','Emagrecimento sem efeitos do GH completo'],
ARRAY['Gravidez','Câncer ativo'],
250, 300, 'mcg', '1x ao dia (em jejum)', 'SC', '3-6 meses',
'~30 minutos', 'Refrigerado após reconstituição',
ARRAY['Tirzepatida','Semaglutida'],
ARRAY[],
ARRAY['Heffernan M et al. (2001) - The effect of human GH and its lipolytic fragment (AOD9604) on lipid metabolism','Ng FM et al. (2000) - Metabolic studies of a synthetic lipolytic domain (AOD9604) of human growth hormone'],
ARRAY['lipólise','gordura','metabolismo','HGH','fragmento'], false),

('melanotan-ii', 'Melanotan II', '⚫', 'Sexual', 'Análogo α-MSH', 'avancado',
'Análogo sintético do α-MSH (hormônio estimulador de melanócitos) com efeitos sobre pigmentação, libido e função erétil.',
'Ativa receptores melanocortina (MC1R para pigmentação, MC3R/MC4R para libido e função sexual). O efeito sexual foi descoberto acidentalmente durante estudos de proteção solar. Age centralmente via sistema dopaminérgico.',
ARRAY['Disfunção erétil (uso off-label)','Aumento de libido','Bronzeamento (uso off-label)','Pesquisa em transtornos sexuais'],
ARRAY['Histórico de melanoma','Nevos displásicos','Hipertensão não controlada','Doença cardiovascular grave'],
500, 1000, 'mcg', '1x ao dia (fase de carga), reduzir em manutenção', 'SC', '2-4 semanas (carga)',
'~1-2 horas', 'Refrigerado, protegido da luz',
ARRAY[],
ARRAY['Medicamentos vasoativos'],
ARRAY['Wessells H et al. (2000) - Effect of an α-Melanocyte Stimulating Hormone analog on penile erection','Diamond LE et al. (2004) - A double-blind, placebo-controlled evaluation of the safety, pharmacokinetic properties and pharmacodynamic effects of intranasal PT-141'],
ARRAY['libido','disfunção erétil','bronzeamento','melanocortina','sexual'], false),

('pt-141', 'PT-141 (Bremelanotida)', '💜', 'Sexual', 'Agonista MC3R/MC4R', 'avancado',
'Análogo do Melanotan II com maior seletividade para receptores sexuais e sem efeitos de bronzeamento. Aprovado pelo FDA para disfunção sexual hipoativa feminina.',
'Agonista seletivo dos receptores melanocortina MC3R e MC4R no sistema nervoso central. Diferente de medicamentos como sildenafila, age centralmente no desejo sexual e não perifericamente na vascularização.',
ARRAY['Disfunção sexual hipoativa feminina (aprovado FDA como Vyleesi)','Disfunção erétil masculina','Aumento de libido'],
ARRAY['Hipertensão cardiovascular','Histórico de melanoma','Gravidez'],
500, 1750, 'mcg', '1x por ocasião (45 min antes da atividade sexual)', 'SC', 'Por demanda',
'~2-3 horas', 'Refrigerado',
ARRAY[],
ARRAY['Anti-hipertensivos (pode potencializar)'],
ARRAY['Clayton AH et al. (2016) - Bremelanotide for Female Sexual Dysfunctions in Premenopausal Women'],
ARRAY['libido','sexual','feminino','aprovado FDA','melanocortina'], false),

('ghrp-6', 'GHRP-6', '🟠', 'GH/Composição', 'Secretagogo GH', 'intermediario',
'Hexapeptídeo secretagogo de GH com forte efeito de aumento de apetite. Um dos primeiros secretagogos sintéticos de GH desenvolvidos.',
'Agonista do receptor de grelina que estimula liberação pulsátil de GH e também aumenta grelina plasmática (daí o forte efeito orexigênico). Aumenta cortisol e prolactina em doses elevadas — limitação importante.',
ARRAY['Estímulo de GH','Aumento de apetite (útil em caquexia)','Ganho de massa muscular','Recuperação'],
ARRAY['Câncer (estímulo GH)','Obesidade (aumento de apetite)','Intolerância a cortisol elevado'],
100, 300, 'mcg', '2-3x ao dia em jejum', 'SC', '8-12 semanas',
'~15-60 minutos', 'Refrigerado',
ARRAY['CJC-1295','MOD-GRF(1-29)'],
ARRAY['Refeições ricas em carboidratos (bloqueia liberação de GH)'],
ARRAY['Bowers CY et al. (1991) - A new dimension on the hypothalamic-pituitary axis: entry and transit of peptides into the brain'],
ARRAY['GH','secretagogo','apetite','grelina','composição corporal'], false),

('mod-grf', 'MOD-GRF(1-29)', '🟡', 'GH/Composição', 'Análogo GHRH curto', 'intermediario',
'Versão modificada do GHRH(1-29) com maior estabilidade metabólica. Sem conjugação DAC — meia-vida curta que imita melhor o padrão fisiológico de GH.',
'Mesma ação do CJC-1295 mas sem DAC: estimula receptores GHRH hipofisários gerando pulso de GH. A meia-vida de ~30 minutos permite uso sincronizado com pulsos naturais de GH, especialmente noturno.',
ARRAY['Padrão fisiológico de estimulação de GH','Combinação com secretagogos (GHRP)','Composição corporal','Anti-aging'],
ARRAY['Acromegalia','Câncer ativo'],
100, 200, 'mcg', '2-3x ao dia (30 min antes de refeições ou ao dormir)', 'SC', '8-12 semanas',
'~30 minutos', 'Refrigerado',
ARRAY['Ipamorelin','GHRP-6','GHRP-2'],
ARRAY['Somatostatina','Insulina elevada pós-prandial'],
ARRAY['Walker RF et al. - Synthetic GRF analogs'],
ARRAY['GH','GHRH','fisiológico','composição','pulso'], false),

('peptideo-2', 'GHRP-2', '🔶', 'GH/Composição', 'Secretagogo GH', 'intermediario',
'Secretagogo de segunda geração com potência superior ao GHRP-6 e menor efeito orexigênico. Aumenta GH de forma robusta mas com algum efeito em cortisol.',
'Agonista seletivo do receptor GHS-R1a com alta afinidade. Produz pulsos de GH maiores que o GHRP-6 com menos aumento de apetite. Ainda eleva cortisol e prolactina em doses altas.',
ARRAY['Estimulação potente de GH','Composição corporal','Recuperação muscular'],
ARRAY['Câncer ativo','Histórico de acromegalia'],
100, 300, 'mcg', '2-3x ao dia em jejum', 'SC', '8-12 semanas',
'~30-60 minutos', 'Refrigerado',
ARRAY['CJC-1295','MOD-GRF(1-29)'],
ARRAY['Alimentos (especialmente gorduras e carboidratos)'],
ARRAY['Laferrere B et al. (1995) - Growth hormone-releasing peptide-2'],
ARRAY['GH','secretagogo','potente','composição','recuperação'], false),

('sermorelin', 'Sermorelin', '🔹', 'GH/Composição', 'Análogo GHRH', 'iniciante',
'Análogo sintético do GHRH com os primeiros 29 aminoácidos. Aprovado pelo FDA para diagnóstico e tratamento de deficiência de GH. Considerado o mais fisiológico dos estimuladores de GH.',
'Estimula receptores GHRH na hipófise anterior de forma fisiológica, mantendo o feedback negativo natural. Por isso, não suprime o eixo GH-IGF1 como o HGH exógeno faz.',
ARRAY['Deficiência de GH (aprovado FDA)','Anti-aging','Composição corporal','Melhora de sono','Recuperação'],
ARRAY['Acromegalia','Tumores hipofisários'],
200, 500, 'mcg', '1x ao dia (antes de dormir)', 'SC', '3-6 meses',
'~10-20 minutos', 'Refrigerado',
ARRAY['Ipamorelin','GHRP-2'],
ARRAY[],
ARRAY['Walker RF (2006) - Sermorelin: a better approach to management of adult-onset growth hormone insufficiency'],
ARRAY['GH','GHRH','fisiológico','sono','anti-aging'], false),

('hexarelin', 'Hexarelin', '🔷', 'GH/Composição', 'Secretagogo potente', 'avancado',
'Secretagogo de GH mais potente disponível. Produz os maiores pulsos de GH entre todos os secretagogos, mas com dessensibilização rápida e efeitos em cortisol.',
'Agonista GHS-R1a com a maior afinidade e potência entre secretagogos. Produz pulsos de GH 2-3x maiores que o Ipamorelin. A dessensibilização ocorre rapidamente com uso contínuo — protocolos devem ser cíclicos.',
ARRAY['Estimulação máxima de GH','Composição corporal avançada','Pesquisa científica'],
ARRAY['Câncer','Acromegalia','Resistência à insulina severa'],
100, 200, 'mcg', '2x ao dia (com dias de descanso)', 'SC', '4-6 semanas (ciclos curtos)',
'~30 minutos', 'Refrigerado',
ARRAY['MOD-GRF(1-29)'],
ARRAY['Uso contínuo (dessensibilização)'],
ARRAY['Laron Z et al. (1995) - IGF-1 treatment in patients with Laron syndrome'],
ARRAY['GH','potente','secretagogo','avançado','dessensibilização'], false),

('igf-1-lr3', 'IGF-1 LR3', '💚', 'GH/Composição', 'Fator de crescimento', 'avancado',
'Análogo do IGF-1 (Insulin-like Growth Factor 1) com substituição de arginina por ácido glutâmico na posição 3, conferindo maior meia-vida e potência.',
'Liga-se a receptores IGF-1 em músculo esquelético, fígado e outros tecidos, estimulando hipertrofia muscular, diferenciação celular e síntese proteica. O LR3 tem menor afinidade pelas proteínas ligantes (IGFBPs), resultando em maior biodisponibilidade.',
ARRAY['Hipertrofia muscular avançada','Recuperação de lesões musculares graves','Déficits de crescimento'],
ARRAY['Câncer (estímulo mitogênico forte)','Diabetes (hipoglicemia)','Acromegalia','Retinopatia diabética'],
20, 120, 'mcg', '1x ao dia (pós-treino)', 'SC (local) ou IM', '4-6 semanas',
'~20-30 horas', 'Refrigerado, muito sensível à temperatura',
ARRAY['CJC-1295/Ipamorelin (seqüencial)'],
ARRAY['Insulina (hipoglicemia severa)'],
ARRAY['Firth SM & Baxter RC (2002) - Cellular actions of the insulin-like growth factor binding proteins'],
ARRAY['IGF-1','fator de crescimento','hipertrofia','avançado','músculo'], false),

('follistatina', 'Follistatina 344', '💛', 'GH/Composição', 'Inibidor miostatina', 'avancado',
'Glicoproteína que inibe a miostatina, principal regulador negativo do crescimento muscular. Uso extremamente específico e ainda em fase de pesquisa para uso humano.',
'Liga-se e neutraliza a miostatina (GDF-8), que normalmente limita a hipertrofia muscular. Também inibe activina A e B. Animais knockout para miostatina apresentam desenvolvimento muscular 2-3x acima do normal.',
ARRAY['Hipertrofia muscular extrema (pesquisa)','Doenças musculares degenerativas (pesquisa)'],
ARRAY['Uso em humanos não amplamente estudado','Câncer','Gravidez'],
50, 100, 'mcg', 'Protocolos variáveis (uso em pesquisa)', 'SC (intramuscular local)', '10-30 dias',
'~24 horas', 'Refrigerado, frágil',
ARRAY[],
ARRAY['Miostatina exógena'],
ARRAY['Lee SJ & McPherron AC (2001) - Regulation of myostatin activity and muscle growth'],
ARRAY['miostatina','hipertrofia','músculo','pesquisa','avançado'], false),

('selank', 'Selank', '🧠', 'Longevidade', 'Nootropic/Ansiolítico', 'iniciante',
'Heptapeptídeo sintético derivado da tuftsin com propriedades ansiolíticas, nootrópicas e imunomoduladoras. Aprovado na Rússia para transtornos de ansiedade.',
'Modula o sistema GABA-A de forma semelhante a benzodiazepínicos mas sem dependência ou sedação. Aumenta BDNF (fator neurotrófico), modula serotonina e dopamina, e tem efeitos imunomoduladores via IL-6.',
ARRAY['Ansiedade generalizada','Melhora cognitiva','Depressão leve','Imunomodulação','Neuroproteção'],
ARRAY['Gravidez','Uso com depressores do SNC'],
250, 500, 'mcg', '1-2x ao dia', 'SC ou intranasal', '2-4 semanas',
'~1 hora', 'Refrigerado',
ARRAY['Semax','BPC-157'],
ARRAY['Benzodiazepínicos (potencialização)'],
ARRAY['Semenova TP et al. (2010) - Selank treatment affects the behavior and functional neurochemistry','Zozulya AA et al. (2001) - Selank decreases anxiety and modulates cytokine levels'],
ARRAY['ansiedade','cognição','GABA','nootropic','neuroproteção'], false),

('semax', 'Semax', '🧩', 'Longevidade', 'Nootropic', 'iniciante',
'Heptapeptídeo sintético derivado do ACTH com potentes propriedades nootrópicas e neuroprotetoras. Aprovado na Rússia e amplamente estudado.',
'Aumenta BDNF e NGF no hipocampo e córtex cerebral. Modula receptores dopaminérgicos e serotonérgicos. Tem efeito anti-inflamatório central e neuroprotetor em modelo de isquemia.',
ARRAY['Melhora cognitiva e memória','Neuroproteção','Recuperação de AVC (pesquisa)','Déficit de atenção','Depressão'],
ARRAY['Gravidez','Epilepsia não controlada'],
200, 900, 'mcg', '1-2x ao dia', 'SC ou intranasal', '2-4 semanas',
'~1 hora', 'Refrigerado',
ARRAY['Selank','BPC-157'],
ARRAY[],
ARRAY['Dolotov OV et al. (2006) - Semax stimulates production of BDNF in rat brain regions','Manchenko DM et al. (2012) - Semax affects dynorphin A content'],
ARRAY['cognição','memória','BDNF','neuroproteção','nootropic'], false),

('dsip', 'DSIP', '😴', 'Longevidade', 'Modulador do sono', 'iniciante',
'Delta Sleep-Inducing Peptide — peptídeo nonapeptídeo que induz naturalmente o sono delta (sono profundo) e tem múltiplos efeitos neuroendócrinos.',
'Modula a liberação de vários hormônios hipofisários, estimula GH durante o sono e tem propriedades antioxidantes. O sono delta profundo é crítico para consolidação de memória e recuperação física.',
ARRAY['Insônia','Melhora da qualidade do sono','Aumento de GH noturno','Antioxidação','Redução de estresse'],
ARRAY['Gravidez'],
200, 400, 'mcg', '1x antes de dormir', 'SC', '2-4 semanas',
'~2-3 horas', 'Refrigerado',
ARRAY['Ipamorelin (sono)','Sermorelin (sono)'],
ARRAY[],
ARRAY['Monnier M et al. (1977) - The delta sleep-inducing peptide','Graf MV & Kastin AJ (1986) - Delta-sleep-inducing peptide (DSIP): a review'],
ARRAY['sono','delta','insônia','recuperação','GH noturno'], false),

('epithalon', 'Epitalon', '⏳', 'Longevidade', 'Telomerase', 'avancado',
'Tetrapeptídeo sintético derivado da epitalamina (extrato da glândula pineal). Um dos peptídeos com mais evidências de efeitos anti-aging a nível celular.',
'Ativa a telomerase, enzima responsável pelo alongamento dos telômeros — estruturas que encurtam a cada divisão celular e limitam o número de divisões (senescência de Hayflick). Também regula a melatonina e tem efeitos antioxidantes.',
ARRAY['Anti-aging celular','Longevidade','Melhora de sono (melatonina)','Suporte à função pineal','Antioxidação'],
ARRAY['Câncer (ativação de telomerase pode favorecer células cancerígenas)'],
5000, 10000, 'mcg', '1x ao dia por 10-20 dias (protocolo)', 'SC', '10-20 dias, 1-2x ao ano',
'~30 minutos', 'Refrigerado',
ARRAY['DSIP','GHK-Cu'],
ARRAY[],
ARRAY['Khavinson VK et al. (2003) - Epithalon peptide induces telomerase activity and telomere elongation in human somatic cells','Anisimov VN et al. (2003) - Effect of Epitalon on biomarkers of aging'],
ARRAY['telômeros','longevidade','anti-aging','epigenética','telomerase'], false),

('ll-37', 'LL-37', '🛡️', 'Longevidade', 'Peptídeo antimicrobiano', 'avancado',
'Único peptídeo antimicrobiano catelicidina humano. Parte fundamental da imunidade inata, com ação antimicrobiana de amplo espectro e múltiplos efeitos imunomoduladores.',
'Permeabiliza e destrói membranas bacterianas, fúngicas e de células virais. Modula resposta inflamatória, estimula angiogênese e migração celular. Deficiência de LL-37 está associada a infecções recorrentes e doenças autoimunes.',
ARRAY['Infecções recorrentes','Imunodeficiência','Cicatrização','Pesquisa anti-infecciosa'],
ARRAY['Doenças autoimunes ativas','Uso com cautela em inflamação sistêmica'],
100, 500, 'mcg', 'Variável conforme indicação', 'SC local ou sistêmica', '2-4 semanas',
'~30-60 minutos', 'Refrigerado',
ARRAY['BPC-157','GHK-Cu'],
ARRAY[],
ARRAY['Zanetti M (2004) - Cathelicidins, multifunctional peptides of the innate immunity','Durr UH et al. (2006) - LL-37, the only human member of the cathelicidin family of antimicrobial peptides'],
ARRAY['antimicrobiano','imunidade','cathelicidina','infecção','imunomodulação'], false),

('ck2-18', 'CK2.18', '🦴', 'Recuperação', 'Regeneração óssea', 'avancado',
'Peptídeo derivado da caseína do leite com propriedades de estimulação de osteoblastos e regeneração óssea. Promissor em pesquisa de osteoporose.',
'Estimula diferenciação e atividade de osteoblastos (células formadoras de osso) sem afetar osteoclastos. Aumenta mineralização óssea e síntese de colágeno tipo I.',
ARRAY['Osteoporose','Regeneração óssea pós-fratura','Densidade mineral óssea'],
ARRAY['Insuficiência renal severa'],
200, 400, 'mcg', '1x ao dia', 'SC', '8-12 semanas',
'~4 horas', 'Refrigerado',
ARRAY['GHK-Cu','BPC-157'],
ARRAY[],
ARRAY['Pedraza CE et al. (2008) - The role of CK2.18 in osteoblast differentiation'],
ARRAY['osso','osteoporose','osteoblasto','densidade','regeneração'], false),

('humanin', 'Humanina', '❤️', 'Longevidade', 'Mitocondrial', 'avancado',
'Peptídeo mitocondrial (codificado pelo genoma mitocondrial) com potentes efeitos neuroprotetores e anti-aging sistêmico. Diminui com a idade.',
'Ativa receptor FPRL2 e sinalização STAT3. Protege neurônios do Alzheimer, reduz estresse oxidativo mitocondrial, melhora sensibilidade à insulina e tem efeitos cardiovasculares protetores.',
ARRAY['Neuroproteção (Alzheimer)','Anti-aging mitocondrial','Proteção cardiovascular','Melhora metabólica'],
ARRAY['Uso em humanos ainda em pesquisa'],
50, 200, 'mcg', 'Protocolos variáveis', 'SC', 'Pesquisa',
'~1-2 horas', 'Refrigerado',
ARRAY['Epitalon','GHK-Cu'],
ARRAY[],
ARRAY['Hashimoto Y et al. (2001) - A rescue factor abolishing neuronal cell death by a wide spectrum of familial Alzheimer''s disease genes and Abeta','Lee C et al. (2015) - The mitochondrial-derived peptide MOTS-c promotes metabolic homeostasis'],
ARRAY['mitocondria','neuroproteção','Alzheimer','anti-aging','longevidade'], false),

('mots-c', 'MOTS-c', '⚡', 'Longevidade', 'Mitocondrial', 'avancado',
'Peptídeo mitocondrial que regula o metabolismo sistêmico. Atua como "hormônio mitocondrial" com efeitos no músculo esquelético e metabolismo da glicose.',
'Ativa AMPK e suprime via folato-metionina, reduzindo estresse metabólico. Aumenta captação de glicose muscular independente de insulina, reduz gordura visceral e melhora capacidade aeróbica.',
ARRAY['Resistência metabólica','Melhora de performance','Longevidade','Regulação de glicose'],
ARRAY['Uso em humanos ainda em pesquisa'],
5000, 10000, 'mcg', '3-5x por semana', 'SC', 'Pesquisa',
'~2-3 horas', 'Refrigerado',
ARRAY['Humanina','Epitalon'],
ARRAY[],
ARRAY['Lee C et al. (2015) - The mitochondrial-derived peptide MOTS-c promotes metabolic homeostasis and reduces obesity and insulin resistance'],
ARRAY['mitocondria','metabolismo','AMPK','longevidade','performance'], false),

('p21', 'P21', '🧬', 'Longevidade', 'Antifibrótico', 'avancado',
'Peptídeo derivado da proteína p21 (CDKN1A) com propriedades antifibróticas e regenerativas. Em fase de pesquisa para doenças pulmonares e hepáticas.',
'Inibe proliferação celular anormal e fibrose via modulação do ciclo celular. Reduz TGF-β, principal mediador de fibrose. Efeitos anti-senescência e de rejuvenescimento tecidual.',
ARRAY['Fibrose hepática (pesquisa)','Fibrose pulmonar (pesquisa)','Anti-senescência'],
ARRAY['Uso humano em pesquisa apenas'],
500, 1000, 'mcg', 'Protocolos de pesquisa', 'SC', 'Pesquisa',
'Desconhecida', 'Refrigerado',
ARRAY['BPC-157','GHK-Cu'],
ARRAY[],
ARRAY['Joubel A et al. (1997) - The human p21(WAF1/CIP1) gene contains two AP-2 binding sites functioning as negative regulatory elements'],
ARRAY['fibrose','antifibrótico','senescência','pesquisa','anti-aging'], false),

('vip', 'VIP', '🫁', 'Longevidade', 'Neuropeptídeo', 'avancado',
'Vasoactive Intestinal Peptide — neuropeptídeo com potentes efeitos anti-inflamatórios, broncodilatadores e imunomoduladores. Pesquisado em doenças autoimunes e COVID-19.',
'Liga-se a receptores VPAC1 e VPAC2 modulando cAMP. Reduz citocinas pró-inflamatórias (TNF-α, IL-6, IL-12), aumenta IL-10. Dilata brônquios e vasos, reduz hipertensão pulmonar.',
ARRAY['Doenças autoimunes','Hipertensão pulmonar','Síndrome pós-COVID (pesquisa)','Anti-inflamatório sistêmico'],
ARRAY['Hipotensão','Gravidez'],
50, 100, 'mcg', '2x ao dia', 'SC ou inalatória', '2-4 semanas',
'~1-2 minutos (IV), horas (SC)', 'Refrigerado, sensível',
ARRAY['BPC-157'],
ARRAY[],
ARRAY['Gonzalez-Rey E et al. (2006) - Vasoactive intestinal peptide generates human tolerogenic dendritic cells that induce CD4 and CD8 regulatory T cells','Abad C et al. (2010) - Therapeutic effects of vasoactive intestinal peptide in the trinitrobenzene sulfonic acid mice model of Crohn''s disease'],
ARRAY['anti-inflamatório','autoimune','broncodilatador','imunomodulação','neuropeptídeo'], false),

('kisspeptin', 'Kisspeptina-10', '🌡️', 'Sexual', 'Regulador hormonal', 'avancado',
'Neuropeptídeo que controla a pulsatilidade do GnRH e consequentemente todo o eixo reprodutivo. Essencial para fertilidade e produção de testosterona/estrogênio.',
'Ativa receptor KISS1R nos neurônios KNDy do hipotálamo, estimulando pulsos de GnRH. O GnRH estimula LH e FSH na hipófise, que por sua vez estimulam produção de testosterona/estrogênio e maturação de gametas.',
ARRAY['Hipogonadismo hipogonadotrófico','Infertilidade','Reposição hormonal (pesquisa)','Melhora de libido'],
ARRAY['Tumores gonadais','Puberdade precoce','Gravidez (exceto indicação específica)'],
1000, 10000, 'mcg', 'Protocolos variáveis (pulsátil ideal)', 'SC ou IV', 'Pesquisa',
'~24-68 minutos', 'Refrigerado',
ARRAY[],
ARRAY['Agonistas GnRH contínuos (downregulation)'],
ARRAY['Dhillo WS et al. (2005) - Kisspeptin-54 stimulates the hypothalamic-pituitary gonadal axis in human males','Skorupskaite K et al. (2014) - The kisspeptin-GnRH pathway in human reproductive health and disease'],
ARRAY['testosterona','fertilidade','GnRH','reprodutivo','hormonal'], false),

('gip', 'GIP', '🍽️', 'Emagrecimento', 'Incretina', 'intermediario',
'Glucose-dependent Insulinotropic Peptide — incretina produzida no duodeno em resposta à alimentação. Parte do mecanismo da tirzepatida.',
'Estimula secreção de insulina glicose-dependente, reduz esvaziamento gástrico e tem efeitos diretos no tecido adiposo (lipólise) e osso (proteção). Diferente do GLP-1, também age perifericamente no tecido adiposo.',
ARRAY['Entendimento de mecanismo da tirzepatida','Diabetes tipo 2','Controle metabólico'],
ARRAY['Hipoglicemia'],
100, 500, 'mcg', 'Variável', 'SC', 'Pesquisa/educacional',
'~7 minutos (nativo)', 'Refrigerado',
ARRAY['GLP-1','Tirzepatida'],
ARRAY[],
ARRAY['Drucker DJ (2006) - The biology of incretin hormones','Baggio LL & Drucker DJ (2007) - Biology of incretins: GLP-1 and GIP'],
ARRAY['incretina','GIP','metabolismo','diabetes','tirzepatida'], false);

-- Índice para busca
CREATE INDEX IF NOT EXISTS idx_peptideos_categoria ON public.peptideos(categoria);
CREATE INDEX IF NOT EXISTS idx_peptideos_nivel ON public.peptideos(nivel);
CREATE INDEX IF NOT EXISTS idx_peptideos_slug ON public.peptideos(slug);
